let startcuts = [
    [
        "Google",
        "http://www.google.com/",
        "https://cdn.iconscout.com/icon/free/png-256/free-google-1772223-1507807.png",
    ],
    [
        "Gmail",
        "http://www.gmail.com/",
        "https://cdn-icons-png.flaticon.com/512/732/732200.png",
    ],
    [
        "Photos",
        "http://www.photos.google.com/",
        "https://cdn-icons-png.flaticon.com/512/2991/2991131.png",
    ],
    [
        "Calendar",
        "https://calendar.google.com/calendar/r?pli=1",
        "https://cdn-icons-png.flaticon.com/512/5968/5968499.png",
    ],
    [
        "Maps",
        "https://www.google.com/maps",
        "https://cdn-icons-png.flaticon.com/512/1865/1865269.png",
    ],
    [
        "Keep",
        "https://drive.google.com/keep/",
        "https://cdn-icons-png.flaticon.com/512/2965/2965358.png",
    ],
    [
        "youTube",
        "http://www.youtube.com/",
        "https://cdn-icons-png.flaticon.com/512/1384/1384060.png",
    ],
    [
        "Instagram",
        "http://www.instagram.com/",
        "https://cdn-icons-png.flaticon.com/512/174/174855.png",
    ],
    [
        "Github",
        "http://www.github.com/",
        "https://cdn-icons-png.flaticon.com/512/733/733553.png",
    ],
    [
        "Gemini",
        "https://bard.google.com/chat",
        "https://seeklogo.com/images/G/google-gemini-logo-A5787B2669-seeklogo.com.png",
    ],
    [
        "ChatGPT",
        "https://chat.openai.com/chat",
        "https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/chatgpt-icon.png",
    ],
    [
        "Bing",
        "https://www.bing.com/search?q=Bing+AI&qs=BC&sc=11-0&cvid=3C7623DF1FB14E998597DEC426ECF743&FORM=ASCHAT&asbe=BC&showconv=1&sp=11&lq=0",
        "https://play-lh.googleusercontent.com/17zMqR9Gx7pQxZh9Q1Zr_VGl7Ja5CnO4C70Ry0gJRXzXVcE6H4FwCZShVPRnF76w-g",
    ],
    [
        "Facebook",
        "www.facebook.com",
        "https://cdn.iconscout.com/icon/free/png-256/free-facebook-logo-2019-1597680-1350125.png?f=webp",
    ],
    [
        "Twitter",
        "www.twitter.com",
        "https://cdn.icon-icons.com/icons2/729/PNG/512/twitter_icon-icons.com_62751.png",
    ],
    [
        "9gag",
        "https://9gag.com/",
        "https://cdn-icons-png.flaticon.com/512/3938/3938118.png",
    ],
];

export default startcuts;